services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:${PORT:-8080}" # Localhost:8080. Container and image: env.PORT or 8080
    environment:
      - PORT=${PORT}
      - RATE_LIMIT_IP_MAX_REQUEST=${RATE_LIMIT_IP_MAX_REQUEST}
      - RATE_LIMIT_IP_BLOCK_DURATION=${RATE_LIMIT_IP_BLOCK_DURATION}
      - RATE_LIMIT_TOKEN_MAX_REQUEST=${RATE_LIMIT_TOKEN_MAX_REQUEST}
      - RATE_LIMIT_TOKEN_BLOCK_DURATION=${RATE_LIMIT_TOKEN_BLOCK_DURATION}
      - REDIS_HOST=${REDIS_HOST}
    depends_on:
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"
